version: '3'
services:
  ## Setup db
  postgres:
    image: postgres:10.4
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_LOCAL_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  ## Setup server
  app:
    build: ./backend
    depends_on:
      - postgres
    environment:
      DEV_DATABASE_URL: ${DEV_DATABASE_URL}
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: "development"
      HOST: ${APP_SERVER_HOST}
      PORT: ${APP_SERVER_PORT}
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    expose:
      - ${APP_SERVER_PORT}
    volumes:
      - ./backend/:/app/
